name: StayPut
version: 3.0.0c
api-version: 1.18
author: Zander van der Meer, pmdevita
main: nl.zandervdm.stayput.Main
website: http://zandervdm.nl
depend: [Multiverse-Core]
softdepend: [Multiverse-Portals]
commands:
    stayput:
        description: Main command
        usage: /stayput <command>
        aliases: [stay, sp]